server:
  port: 8083

spring:
  application:
    name: user-service
  data:
    mongodb:
      database: User
      host: localhost
      port: 27017

eureka:
  instance:
    hostname: user-service
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
