version: '3.7'
services:

  #  ARCHITECTURAL SERVICES

  service-discovery:
    container_name: service-discovery
    image: lorenzos98/civiclife:service-discovery
    #build: service-discovery
    ports:
      - "8761:8761"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  api-gateway:
    container_name: api-gateway
    image: lorenzos98/civiclife:api-gateway
    #build: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  #  ----------------------------------------------
  #  APPLICATION SERVICES

  user-service:
    #build: user-service
    image: lorenzos98/civiclife:user-service
    container_name: user-service
    ports:
      - "8083:8083"
    links:
      - user-db
    depends_on:
      - user-db
      - service-discovery
      - rabbitmq
      - oauth-service
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  initiative-service:
    #build: initiative-service
    image: lorenzos98/civiclife:initiative-service
    container_name: initiative-service
    links:
      - initiative-db
    ports:
      - "8082:8082"
    depends_on:
      - initiative-db
      - service-discovery
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  oauth-service:
    #build: oauth-service
    image: lorenzos98/civiclife:oauth-service
    container_name: oauth-service
    links:
      - token-db
    depends_on:
      - token-db
      - service-discovery
      - rabbitmq
    ports:
      - "8085:8085"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  vote-service:
    #build: vote-service
    image: lorenzos98/civiclife:vote-service
    container_name: vote-service
    ports:
      - "8084:8084"
    links:
      - vote-db
    depends_on:
      - vote-db
      - service-discovery
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  external-resources-service:
    #build: external-resources-service
    image: lorenzos98/civiclife:external-resources-service
    container_name: external-resources-service
    links:
      - external-resources-db
    depends_on:
      - external-resources-db
      - service-discovery
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  #  ----------------------------------------------
  #  DATABASES

  initiative-db:
    image: mongo:latest
    container_name: initiative-db
    restart: unless-stopped
    volumes:
      - initiative-db:/var/lib/initiativeDB/data
    ports:
      - "27018:27017"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  user-db:
    image: mongo:latest
    container_name: user-db
    restart: unless-stopped
    volumes:
      - user-db:/var/lib/userDB/data
    ports:
      - "27019:27017"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  token-db:
    image: mongo:latest
    container_name: token-db
    restart: unless-stopped
    volumes:
      - token-db:/var/lib/tokenDB/data
    ports:
      - "27021:2017"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  vote-db:
    image: mongo:latest
    container_name: vote-db
    restart: unless-stopped
    volumes:
      - vote-db:/var/lib/voteDB/data
    ports:
      - "27020:27017"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

  external-resources-db:
    image: mongo:latest
    container_name: external-resources-db
    restart: unless-stopped
    volumes:
      - external-resources-db:/var/lib/external-resourcesDB/data
    ports:
      - "27022:27017"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - clnet

volumes:
  external-resources-db:
  user-db:
  vote-db:
  token-db:
  initiative-db:
networks:
  clnet:
    driver: bridge