version: '3.7'
services:
  #  ARCHITECTURAL SERVICES
  service-discovery:
    container_name: service-discovery
    image: service-discovery-1.0
    build: service-discovery
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    container_name: api-gateway
    image: api-gateway-1.0
    build: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  #  ----------------------------------------------
  #  APPLICATION SERVICES
  external-resources-service:
    build: external-resources-service
    image: external-resources-service-1.0
    container_name: external-resources-service
    depends_on:
      - external-resources-db
      - service-discovery
    ports:
      - "8081:8081"
    networks:
      - civiclife-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  initiative-service:
    build: initiative-service
    image: initiative-service-1.0
    container_name: initiative-service
    links:
      - initiative-db
    ports:
      - "8082:8082"
    depends_on:
      - initiative-db
      - service-discovery
    networks:
      - civiclife-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build: user-service
    image: user-service-1.0
    container_name: user-service
    ports:
      - "8083:8083"
    links:
      - user-db
    depends_on:
      - user-db
      - service-discovery
    networks:
      - civiclife-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  vote-service:
    build: vote-service
    image: vote-service-1.0
    container_name: vote-service
    ports:
      - "8084:8084"
    links:
      - vote-db
    depends_on:
      - vote-db
      - service-discovery
    networks:
      - civiclife-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  #  ----------------------------------------------
  #  DATABASES

  external-resources-db:
    container_name: external-resources-db
    image: postgres
    ports:
      - "5432"
    volumes:
      - external-resources-db:/var/lib/external-resourcesDB/data
    networks:
      - civiclife-network
    environment:
      POSTGRES_DB: ExternalResources
      POSTGRES_USER: taass
      POSTGRES_PASSWORD: taass
      restart: unless-stopped

  initiative-db:
    image: mongo:latest
    container_name: initiative-db
    restart: unless-stopped
    volumes:
      - initiative-db:/var/lib/initiativeDB/data
    ports:
      - "27017:27017"
    networks:
      - civiclife-network

  user-db:
    image: mongo:latest
    container_name: user-db
    restart: unless-stopped
    volumes:
      - user-db:/var/lib/userDB/data
    ports:
      - "27018:27017"
    networks:
      - civiclife-network

  vote-db:
    image: mongo:latest
    container_name: vote-db
    restart: unless-stopped
    volumes:
      - vote-db:/var/lib/voteDB/data
    ports:
      - "27019:27017"
    networks:
      - civiclife-network

volumes:
  external-resources-db:
  initiative-db:
  user-db:
  vote-db:
networks:
  civiclife-network:
    driver: bridge