apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:management-alpine
    name: rabbitmq
    ports:
    - containerPort: 5672
    - containerPort: 15672
    resources: {}
  restartPolicy: OnFailure
status: {}
