apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: token-db
  name: token-db
spec:
  containers:
  - image: mongo:latest
    name: token-db
    ports:
    - containerPort: 2017
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/tokenDB/data
      name: token-db
  restartPolicy: OnFailure
  volumes:
  - name: token-db
    persistentVolumeClaim:
      claimName: token-db
status: {}
