apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: token-db
  name: token-db
spec:
  ports:
  - name: "27021"
    port: 27021
    targetPort: 2017
  selector:
    io.kompose.service: token-db
status:
  loadBalancer: {}
