apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  containers:
  - image: user-service-1.0
    name: user-service
    ports:
    - containerPort: 8083
    resources: {}
  restartPolicy: OnFailure
status: {}
