apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-db
  name: user-db
spec:
  containers:
  - image: mongo:latest
    name: user-db
    ports:
    - containerPort: 27017
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/userDB/data
      name: user-db
  restartPolicy: OnFailure
  volumes:
  - name: user-db
    persistentVolumeClaim:
      claimName: user-db
status: {}
