server:
  port: 8085
  error:
    include-message: always

spring:
  application:
    name: oauth-service
  data:
    mongodb:
      database: Token
      host: token-db
      port: 27017
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 592921883582-daoe1pufsfjspjeo54aur75jiagc2bp9.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 477776624531560
            client-secret: 8e702b37860f7c35c7fcc4c46bcfc601
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka