server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: external-resources-service
  data:
    mongodb:
      database: ExternalResources
      host: external-resources-db
      port: 27017

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka
