server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: external-resources-service
  data:
    mongodb:
      database: ExternalResources
      host: localhost
      port: 27017

eureka:
  instance:
    prefer-ip-address: true
    #hostname: external-resources-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
