version: '3'

services:
  postgresDB:
    container_name: postgresDB
    image: postgres
    ports:
      - "5432"
    volumes:
      - postgresDB:/var/lib/postgresql/data
    networks:
      - civiclife-network
    environment:
      POSTGRES_DB: ExternalResources
      POSTGRES_USER: taass
      POSTGRES_PASSWORD: taass
      restart: unless-stopped

  external-resources-service:
    build: .
    image: external-resources-service
    container_name: external-resources-service
    ports:
      - "8080:8080"
    depends_on:
      - postgresDB
    networks:
      - civiclife-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/ExternalResources
      - SPRING_DATASOURCE_USERNAME=taass
      - SPRING_DATASOURCE_PASSWORD=taass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  postgresDB:
networks:
  civiclife-network:
    driver: bridge