server:
  port: 8083

spring:
  application:
    name: vote-service
  data:
    mongodb:
      database: Vote
      host: vote-db
      port: 27017
eureka:
  instance:
    prefer-ip-address: true
    hostname: vote-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

---
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka