server:
  port: 8082

spring:
  application:
    name: initiative-service
  data:
    mongodb:
      database: Initiative
      host: initiative-db
      port: 27017

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka
