server:
  port: 8083

spring:
  rabbitmq:
    host: user-service
    username: guest
    password: guest
    port: 15672
    template:
      exchange: oauth-exchange
      routing-key: oauth-key
  application:
    name: user-service
  data:
    mongodb:
      database: User
      host: user-db
      port: 27017

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka
